project:
  type: website

website:
  title: "Julia Pocciotti"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/juliapocciotti
      - icon: linkedin
        href: https://www.linkedin.com/in/juliapocciotti/
    
format:
  html:
    theme: 
      - minty
      - styles/styles.scss
    



